/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package creadoranexosffe;

import creadoranexosffe.librerias.Alumno;
import creadoranexosffe.librerias.DatosComunes;
import creadoranexosffe.librerias.EscrituraDatos;
import creadoranexosffe.librerias.FicherosDirectorios;
import creadoranexosffe.librerias.Modulo;
import creadoranexosffe.librerias.RecopilacionDatos;
import java.io.File;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author javimjprofe
 */
public class CreadorAnexosFFE extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreadorAnexosFFE.class.getName());
    private List<Alumno> alumnos = new ArrayList<Alumno>();
    private List<Modulo> modulos = new ArrayList<Modulo>();

    /**
     * Creates new form Principal
     */
    public CreadorAnexosFFE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpTipoAnexo = new javax.swing.ButtonGroup();
        pnlTipoAnexo = new javax.swing.JPanel();
        rdbAnexoI = new javax.swing.JRadioButton();
        rdbAnexoII = new javax.swing.JRadioButton();
        btnGenerarAnexos = new javax.swing.JButton();
        pnlDatosComunes = new javax.swing.JPanel();
        lblCodigoCiclo = new javax.swing.JLabel();
        txtCodigoCiclo = new javax.swing.JTextField();
        lblNombreCiclo = new javax.swing.JLabel();
        txtNombreCiclo = new javax.swing.JTextField();
        lblGrupo = new javax.swing.JLabel();
        txtGrupo = new javax.swing.JTextField();
        lblAnyoEscolar = new javax.swing.JLabel();
        spnCurso = new javax.swing.JSpinner();
        spnAnyoEscolarIni = new javax.swing.JSpinner();
        lblBarraAnyoEscolar = new javax.swing.JLabel();
        spnAnyoEscolarFin = new javax.swing.JSpinner();
        lblCurso = new javax.swing.JLabel();
        lblPobalcion = new javax.swing.JLabel();
        txtPoblacion = new javax.swing.JTextField();
        lblFechaSesion = new javax.swing.JLabel();
        spnFechaSesion = new javax.swing.JSpinner();
        lblFechaFirma = new javax.swing.JLabel();
        spnFechaFirma = new javax.swing.JSpinner();
        pnlAlumnos = new javax.swing.JPanel();
        lblNombreAlumno = new javax.swing.JLabel();
        txtNombreAlumno = new javax.swing.JTextField();
        lblApellidosAlumno = new javax.swing.JLabel();
        txtApellidosAlumno = new javax.swing.JTextField();
        btnAnyadirAlumno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        btnEliminarAlumno = new javax.swing.JButton();
        btnImportarAlumno = new javax.swing.JButton();
        btnVaciarTablaAlumnos = new javax.swing.JButton();
        pnlModulos = new javax.swing.JPanel();
        lblNombreModulo = new javax.swing.JLabel();
        txtCodigoModulo = new javax.swing.JTextField();
        lblCodigoModulo = new javax.swing.JLabel();
        txtNombreModulo = new javax.swing.JTextField();
        btnAnyadirModulo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblModulos = new javax.swing.JTable();
        btnEliminarModulo = new javax.swing.JButton();
        btnImportarModulos = new javax.swing.JButton();
        btnVaciarTablaModulos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Creador Anexos FFE");
        setName("frmPrincipal"); // NOI18N

        pnlTipoAnexo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Anexos"));

        btnGrpTipoAnexo.add(rdbAnexoI);
        rdbAnexoI.setSelected(true);
        rdbAnexoI.setText("Anexo I");
        rdbAnexoI.addActionListener(this::rdbAnexoIActionPerformed);

        btnGrpTipoAnexo.add(rdbAnexoII);
        rdbAnexoII.setText("Anexo II");
        rdbAnexoII.addActionListener(this::rdbAnexoIIActionPerformed);

        btnGenerarAnexos.setText("Generar Anexos");
        btnGenerarAnexos.addActionListener(this::btnGenerarAnexosActionPerformed);

        javax.swing.GroupLayout pnlTipoAnexoLayout = new javax.swing.GroupLayout(pnlTipoAnexo);
        pnlTipoAnexo.setLayout(pnlTipoAnexoLayout);
        pnlTipoAnexoLayout.setHorizontalGroup(
            pnlTipoAnexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoAnexoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlTipoAnexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbAnexoII)
                    .addComponent(rdbAnexoI)
                    .addComponent(btnGenerarAnexos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlTipoAnexoLayout.setVerticalGroup(
            pnlTipoAnexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoAnexoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(rdbAnexoI)
                .addGap(18, 18, 18)
                .addComponent(rdbAnexoII)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnGenerarAnexos)
                .addContainerGap())
        );

        pnlDatosComunes.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Comunes"));

        lblCodigoCiclo.setText("Código Ciclo: ");

        lblNombreCiclo.setText("Nombre del Ciclo: ");

        lblGrupo.setText("Grupo: ");

        lblAnyoEscolar.setText("Año Escolar: ");

        spnCurso.setModel(new javax.swing.SpinnerNumberModel(1, 1, 2, 1));
        spnCurso.setName("spnCurso"); // NOI18N

        spnAnyoEscolarIni.setModel(new javax.swing.SpinnerNumberModel(2025, 2025, 2100, 1));

        lblBarraAnyoEscolar.setText("/");

        spnAnyoEscolarFin.setModel(new javax.swing.SpinnerNumberModel(2026, 2026, 2100, 1));

        lblCurso.setText("Curso: ");

        lblPobalcion.setText("Población: ");

        lblFechaSesion.setText("Fecha Sesión de Evaluación");

        spnFechaSesion.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1756677600000L), new java.util.Date(4133977140000L), java.util.Calendar.DAY_OF_MONTH));
        spnFechaSesion.setEditor(new javax.swing.JSpinner.DateEditor(spnFechaSesion, "dd/MMyyyy"));

        lblFechaFirma.setText("Fecha de Firma: ");

        spnFechaFirma.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1756677600000L), new java.util.Date(4133977140000L), java.util.Calendar.DAY_OF_MONTH));
        spnFechaFirma.setEditor(new javax.swing.JSpinner.DateEditor(spnFechaFirma, "dd/MMyyyy"));

        javax.swing.GroupLayout pnlDatosComunesLayout = new javax.swing.GroupLayout(pnlDatosComunes);
        pnlDatosComunes.setLayout(pnlDatosComunesLayout);
        pnlDatosComunesLayout.setHorizontalGroup(
            pnlDatosComunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosComunesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlDatosComunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDatosComunesLayout.createSequentialGroup()
                        .addGroup(pnlDatosComunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosComunesLayout.createSequentialGroup()
                                .addComponent(lblCurso)
                                .addGap(18, 18, 18)
                                .addComponent(spnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblGrupo)
                                .addGap(18, 18, 18)
                                .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDatosComunesLayout.createSequentialGroup()
                                .addComponent(lblCodigoCiclo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNombreCiclo)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblAnyoEscolar)
                                .addGap(18, 18, 18)
                                .addComponent(spnAnyoEscolarIni, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBarraAnyoEscolar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnAnyoEscolarFin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlDatosComunesLayout.createSequentialGroup()
                        .addComponent(lblPobalcion)
                        .addGap(18, 18, 18)
                        .addComponent(txtPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(lblFechaSesion)
                        .addGap(18, 18, 18)
                        .addComponent(spnFechaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFechaFirma)
                        .addGap(18, 18, 18)
                        .addComponent(spnFechaFirma, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
        );
        pnlDatosComunesLayout.setVerticalGroup(
            pnlDatosComunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosComunesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosComunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoCiclo)
                    .addComponent(txtCodigoCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreCiclo)
                    .addComponent(txtNombreCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnyoEscolar)
                    .addComponent(spnAnyoEscolarIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBarraAnyoEscolar)
                    .addComponent(spnAnyoEscolarFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosComunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso)
                    .addComponent(spnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrupo)
                    .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosComunesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaSesion)
                    .addComponent(spnFechaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaFirma)
                    .addComponent(spnFechaFirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPobalcion)
                    .addComponent(txtPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnlAlumnos.setBorder(javax.swing.BorderFactory.createTitledBorder("Alumnos"));

        lblNombreAlumno.setText("Nombre: ");

        lblApellidosAlumno.setText("Apellidos: ");

        btnAnyadirAlumno.setText("Añadir Alumno");
        btnAnyadirAlumno.addActionListener(this::btnAnyadirAlumnoActionPerformed);

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlumnos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblAlumnosMouseReleased(evt);
            }
        });
        tblAlumnos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblAlumnosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlumnos);

        btnEliminarAlumno.setText("Eliminar Alumno");
        btnEliminarAlumno.setEnabled(false);
        btnEliminarAlumno.addActionListener(this::btnEliminarAlumnoActionPerformed);

        btnImportarAlumno.setText("Importar");
        btnImportarAlumno.addActionListener(this::btnImportarAlumnoActionPerformed);

        btnVaciarTablaAlumnos.setText("Vaciar Tabla");
        btnVaciarTablaAlumnos.setEnabled(false);
        btnVaciarTablaAlumnos.addActionListener(this::btnVaciarTablaAlumnosActionPerformed);

        javax.swing.GroupLayout pnlAlumnosLayout = new javax.swing.GroupLayout(pnlAlumnos);
        pnlAlumnos.setLayout(pnlAlumnosLayout);
        pnlAlumnosLayout.setHorizontalGroup(
            pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlumnosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAlumnosLayout.createSequentialGroup()
                        .addComponent(lblNombreAlumno)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreAlumno)
                        .addGap(18, 18, 18)
                        .addComponent(lblApellidosAlumno)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidosAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAlumnosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVaciarTablaAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImportarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnyadirAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        pnlAlumnosLayout.setVerticalGroup(
            pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlumnosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAlumno)
                    .addComponent(txtNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidosAlumno)
                    .addComponent(txtApellidosAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnyadirAlumno))
                .addGap(18, 18, 18)
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlAlumnosLayout.createSequentialGroup()
                        .addComponent(btnImportarAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarAlumno)
                        .addGap(18, 18, 18)
                        .addComponent(btnVaciarTablaAlumnos))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlModulos.setBorder(javax.swing.BorderFactory.createTitledBorder("Módulos"));

        lblNombreModulo.setText("Nombre: ");

        lblCodigoModulo.setText("Código: ");

        btnAnyadirModulo.setText("Añadir Módulo");
        btnAnyadirModulo.addActionListener(this::btnAnyadirModuloActionPerformed);

        tblModulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblModulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblModulosMouseReleased(evt);
            }
        });
        tblModulos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblModulosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblModulos);

        btnEliminarModulo.setText("Eliminar Módulo");
        btnEliminarModulo.setEnabled(false);
        btnEliminarModulo.addActionListener(this::btnEliminarModuloActionPerformed);

        btnImportarModulos.setText("Importar");
        btnImportarModulos.addActionListener(this::btnImportarModulosActionPerformed);

        btnVaciarTablaModulos.setText("Vaciar Tabla");
        btnVaciarTablaModulos.setEnabled(false);
        btnVaciarTablaModulos.addActionListener(this::btnVaciarTablaModulosActionPerformed);

        javax.swing.GroupLayout pnlModulosLayout = new javax.swing.GroupLayout(pnlModulos);
        pnlModulos.setLayout(pnlModulosLayout);
        pnlModulosLayout.setHorizontalGroup(
            pnlModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModulosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlModulosLayout.createSequentialGroup()
                        .addComponent(lblCodigoModulo)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombreModulo)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreModulo))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(pnlModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAnyadirModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImportarModulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVaciarTablaModulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        pnlModulosLayout.setVerticalGroup(
            pnlModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModulosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreModulo)
                    .addComponent(lblCodigoModulo)
                    .addComponent(txtCodigoModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnyadirModulo))
                .addGap(18, 18, 18)
                .addGroup(pnlModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlModulosLayout.createSequentialGroup()
                        .addComponent(btnImportarModulos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarModulo)
                        .addGap(18, 18, 18)
                        .addComponent(btnVaciarTablaModulos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlModulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlTipoAnexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlDatosComunes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatosComunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlTipoAnexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbAnexoIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbAnexoIIActionPerformed
        if (rdbAnexoII.isSelected()) {
            txtCodigoModulo.setEnabled(false);
            txtNombreModulo.setEnabled(false);
            btnAnyadirModulo.setEnabled(false);
            btnImportarModulos.setEnabled(false);
            btnEliminarModulo.setEnabled(false);
            btnVaciarTablaModulos.setEnabled(false);
            tblModulos.setEnabled(false);
            tblModulos.setRowSelectionAllowed(false);
            tblModulos.setColumnSelectionAllowed(false);
            tblModulos.setCellSelectionEnabled(false);
        }
    }//GEN-LAST:event_rdbAnexoIIActionPerformed

    private void rdbAnexoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbAnexoIActionPerformed
        if (rdbAnexoI.isSelected()) {
            txtCodigoModulo.setEnabled(true);
            txtNombreModulo.setEnabled(true);
            btnAnyadirModulo.setEnabled(true);
            btnImportarModulos.setEnabled(true);
            if (modulos.size() > 0) {
                btnVaciarTablaModulos.setEnabled(true);
            }
            tblModulos.clearSelection();
            tblModulos.setEnabled(true);
            tblModulos.setCellSelectionEnabled(true);
            tblModulos.setColumnSelectionAllowed(true);
            tblModulos.setRowSelectionAllowed(true);
        }
    }//GEN-LAST:event_rdbAnexoIActionPerformed

    private void btnAnyadirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnyadirAlumnoActionPerformed
        if (!anyadirAlumno(txtNombreAlumno.getText().trim(), txtApellidosAlumno.getText().trim())) {
            DialogoError dialogoError = new DialogoError(this, true, "El alumno debe tener nombre y apellidos");
            dialogoError.setVisible(true);
        } else {
            txtNombreAlumno.setText("");
            txtApellidosAlumno.setText("");
            btnVaciarTablaAlumnos.setEnabled(true);
        }
    }//GEN-LAST:event_btnAnyadirAlumnoActionPerformed

    private void tblAlumnosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlumnosMouseReleased
        btnEliminarAlumno.setEnabled(tblAlumnos.getSelectedRow() > -1);
    }//GEN-LAST:event_tblAlumnosMouseReleased

    private void tblAlumnosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblAlumnosKeyReleased
        btnEliminarAlumno.setEnabled(tblAlumnos.getSelectedRow() > -1);
    }//GEN-LAST:event_tblAlumnosKeyReleased

    private void btnEliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlumnoActionPerformed
        int filaSeleccionada = tblAlumnos.getSelectedRow();
        DefaultTableModel modelo;
        if (filaSeleccionada > -1) {
            modelo = (DefaultTableModel) tblAlumnos.getModel();
            modelo.removeRow(filaSeleccionada);
            alumnos.remove(filaSeleccionada);
            tblAlumnos.clearSelection();
            btnEliminarAlumno.setEnabled(false);
            btnVaciarTablaAlumnos.setEnabled(alumnos.size() > 0);
        } else {
            DialogoError dialogoError = new DialogoError(this, true, "Debes seleccionar un alumno en la tabla para eliminar");
            dialogoError.setVisible(true);
        }
    }//GEN-LAST:event_btnEliminarAlumnoActionPerformed

    private void btnVaciarTablaAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarTablaAlumnosActionPerformed
        reiniciarTablaAlumnos();
    }//GEN-LAST:event_btnVaciarTablaAlumnosActionPerformed

    private void btnImportarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarAlumnoActionPerformed
        File fichero;
        List<Alumno> alumnosAAnyadir;
        DialogoInformacion dialogoInformacion;
        JFileChooser fc;
        int seleccion;

        if (alumnos.size() > 0) {
            dialogoInformacion = new DialogoInformacion(this, true, "¿Deseas descartar los alumnos existentes en la tabla?");
            if (dialogoInformacion.mostrarMensajeInformacion()) {
                reiniciarTablaAlumnos();
            }
        }

        fc = new JFileChooser();
        fc.setCurrentDirectory(new File("."));
        fc.setFileFilter(new FileNameExtensionFilter("*.CSV", "csv"));
        fc.setAcceptAllFileFilterUsed(false);
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        seleccion = fc.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            fichero = fc.getSelectedFile();
            alumnosAAnyadir = RecopilacionDatos.recopilarAlumnos(fichero);
            if (alumnosAAnyadir == null) {
                DialogoError dialogoError = new DialogoError(this, true, "Ha ocurrido un error durante la importación de alumnos");
                dialogoError.setVisible(true);
                return;
            }
            for (Alumno alumno : alumnosAAnyadir) {
                if (!anyadirAlumno(alumno.getNombre(), alumno.getApellidos())) {
                    DialogoError dialogoError = new DialogoError(this, true, "El alumno debe tener nombre y apellidos");
                    dialogoError.setVisible(true);
                }
            }
            btnVaciarTablaAlumnos.setEnabled(alumnos.size() > 0);
        }
    }//GEN-LAST:event_btnImportarAlumnoActionPerformed

    private void btnAnyadirModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnyadirModuloActionPerformed
        if (!anyadirModulo(txtCodigoModulo.getText().trim(), txtNombreModulo.getText().trim())) {
            DialogoError dialogoError = new DialogoError(this, true, "El módulo debe tener código y nombre");
            dialogoError.setVisible(true);
        } else {
            txtCodigoModulo.setText("");
            txtNombreModulo.setText("");
            btnVaciarTablaModulos.setEnabled(true);
        }
    }//GEN-LAST:event_btnAnyadirModuloActionPerformed

    private void btnEliminarModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarModuloActionPerformed
        int filaSeleccionada = tblModulos.getSelectedRow();
        DefaultTableModel modelo;
        if (filaSeleccionada > -1) {
            modelo = (DefaultTableModel) tblModulos.getModel();
            modelo.removeRow(filaSeleccionada);
            modulos.remove(filaSeleccionada);
            tblModulos.clearSelection();
            btnEliminarModulo.setEnabled(false);
            btnVaciarTablaModulos.setEnabled(modulos.size() > 0);
        } else {
            DialogoError dialogoError = new DialogoError(this, true, "Debes seleccionar un modulo en la tabla para eliminar");
            dialogoError.setVisible(true);
        }
    }//GEN-LAST:event_btnEliminarModuloActionPerformed

    private void btnVaciarTablaModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarTablaModulosActionPerformed
        reiniciarTablaModulos();
    }//GEN-LAST:event_btnVaciarTablaModulosActionPerformed

    private void btnImportarModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarModulosActionPerformed
        File fichero;
        List<Modulo> modulosAAnyadir;
        DialogoInformacion dialogoInformacion;
        JFileChooser fc;
        int seleccion;

        if (modulos.size() > 0) {
            dialogoInformacion = new DialogoInformacion(this, true, "¿Deseas descartar los módulos existentes en la tabla?");
            if (dialogoInformacion.mostrarMensajeInformacion()) {
                reiniciarTablaModulos();
            }
        }

        fc = new JFileChooser();
        fc.setCurrentDirectory(new File("."));
        fc.setFileFilter(new FileNameExtensionFilter("*.CSV", "csv"));
        fc.setAcceptAllFileFilterUsed(false);
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        seleccion = fc.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            fichero = fc.getSelectedFile();
            modulosAAnyadir = RecopilacionDatos.recopilarModulos(fichero);
            if (modulosAAnyadir == null) {
                DialogoError dialogoError = new DialogoError(this, true, "Ha ocurrido un error durante la importación de módulos");
                dialogoError.setVisible(true);
                return;
            }
            for (Modulo modulo : modulosAAnyadir) {
                if (!anyadirModulo(modulo.getCodigo(), modulo.getNombre())) {
                    DialogoError dialogoError = new DialogoError(this, true, "El modulo debe tener nombre y apellidos");
                    dialogoError.setVisible(true);
                }
            }
            btnVaciarTablaModulos.setEnabled(modulos.size() > 0);
        }
    }//GEN-LAST:event_btnImportarModulosActionPerformed

    private void tblModulosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblModulosMouseReleased
        if (tblModulos.isEnabled())
            btnEliminarModulo.setEnabled(true);
    }//GEN-LAST:event_tblModulosMouseReleased

    private void tblModulosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblModulosKeyReleased
        if (tblModulos.isEnabled())
            btnEliminarModulo.setEnabled(true);
    }//GEN-LAST:event_tblModulosKeyReleased

    private void btnGenerarAnexosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarAnexosActionPerformed
        String codigoCiclo = txtCodigoCiclo.getText().trim();
        String nombreCiclo = txtNombreCiclo.getText().trim();
        String grupo = txtGrupo.getText().trim();
        String poblacion = txtPoblacion.getText().trim();
        DialogoError dialogoError;
        DialogoFin dialogoFin;
        JFileChooser fc;
        DatosComunes datosComunes;
        int seleccion;
        File directorio;
        EscrituraDatos escrituraDatos;
        Date fechaSesion;
        Date fechaFirma;

        try {
            if (codigoCiclo.isEmpty() || nombreCiclo.isEmpty() || grupo.isEmpty() || poblacion.isEmpty()) {
                dialogoError = new DialogoError(this, true, "Todos los datos comunes deben estar rellenos");
            } else {
                fechaSesion = (Date) spnFechaSesion.getValue();
                fechaFirma = (Date) spnFechaFirma.getValue();
                datosComunes = new DatosComunes(codigoCiclo, nombreCiclo, (int) spnCurso.getValue(),
                        (int) spnAnyoEscolarIni.getValue(), (int) spnAnyoEscolarFin.getValue(),
                        grupo, poblacion, fechaSesion.toInstant().atZone(ZoneId.systemDefault()).toLocalDate(),
                        fechaFirma.toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
                fc = new JFileChooser();
                fc.setCurrentDirectory(new File("."));
                fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                seleccion = fc.showSaveDialog(this);
                if (seleccion == fc.APPROVE_OPTION) {
                    directorio = fc.getSelectedFile();
                    if(rdbAnexoI.isSelected()){
                        if(!generarAnexosI(datosComunes, directorio)){
                            dialogoError = new DialogoError(this, true, "Ocurrió un error durante la generación de los anexos");
                            dialogoError.setVisible(true);
                            return;
                        }
                    }
                    else{
                        if(!generarAnexosII(datosComunes, directorio)){
                            dialogoError = new DialogoError(this, true, "Ocurrió un error durante la generación de los anexos");
                            dialogoError.setVisible(true);
                            return;
                        }
                    }
                }
                dialogoFin = new DialogoFin(this, true);
                dialogoFin.setVisible(true);
            }
        } catch (Exception e) {
            dialogoError = new DialogoError(this, true, "Ocurrió un error durante la generación de los anexos");
            dialogoError.setVisible(true);
        }
    }//GEN-LAST:event_btnGenerarAnexosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CreadorAnexosFFE().setVisible(true));
    }

    private boolean anyadirAlumno(String nombre, String apellidos) {
        if (!nombre.isEmpty() && !apellidos.isEmpty()) {
            DefaultTableModel modelo = (DefaultTableModel) tblAlumnos.getModel();
            Object[] fila = {nombre, apellidos};
            modelo.addRow(fila);
            alumnos.add(new Alumno(nombre, apellidos));
            return true;
        } else {
            return false;
        }
    }

    private boolean anyadirModulo(String codigo, String nombre) {
        if (!codigo.isEmpty() && !nombre.isEmpty()) {
            DefaultTableModel modelo = (DefaultTableModel) tblModulos.getModel();
            Object[] fila = {codigo, nombre};
            modelo.addRow(fila);
            modulos.add(new Modulo(codigo, nombre));
            return true;
        } else {
            return false;
        }
    }

    private void reiniciarTablaAlumnos() {
        DefaultTableModel modelo = new DefaultTableModel();
        String[] cabecera = {"Nombre", "Apellidos"};
        modelo.setColumnIdentifiers(cabecera);
        tblAlumnos.setModel(modelo);
        tblAlumnos.setDefaultEditor(Object.class, null);
        btnEliminarAlumno.setEnabled(false);
        btnVaciarTablaAlumnos.setEnabled(false);
        alumnos.clear();
    }

    private void reiniciarTablaModulos() {
        DefaultTableModel modelo = new DefaultTableModel();
        String[] cabecera = {"Código", "Nombre"};
        modelo.setColumnIdentifiers(cabecera);
        tblModulos.setModel(modelo);
        tblModulos.setDefaultEditor(Object.class, null);
        btnEliminarModulo.setEnabled(false);
        btnVaciarTablaModulos.setEnabled(false);
        modulos.clear();
    }

    private boolean generarAnexosI(DatosComunes datosComunes, File directorio) {
        EscrituraDatos escrituraDatos = new EscrituraDatos();
        for (Modulo modulo : modulos) {
            FicherosDirectorios.crearCarpeta(directorio.getAbsoluteFile() + "/"
                    + datosComunes.getCodigoCiclo() + "/" + modulo.getCodigo() + "/");
            for (Alumno alumno : alumnos) {
                if (!escrituraDatos.rellenarAnexoI(directorio, alumno, modulo, datosComunes)) {
                    return false;
                }
            }
        }
        return true;
    }

    private boolean generarAnexosII(DatosComunes datosComunes, File directorio) {
        EscrituraDatos escrituraDatos = new EscrituraDatos();
        FicherosDirectorios.crearCarpeta(directorio.getAbsoluteFile() + "/"
                + datosComunes.getCodigoCiclo() + "/");
        for (Alumno alumno : alumnos) {
            if (!escrituraDatos.rellenarAnexoII(directorio, alumno, datosComunes)) {
                return false;
            }
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnyadirAlumno;
    private javax.swing.JButton btnAnyadirModulo;
    private javax.swing.JButton btnEliminarAlumno;
    private javax.swing.JButton btnEliminarModulo;
    private javax.swing.JButton btnGenerarAnexos;
    private javax.swing.ButtonGroup btnGrpTipoAnexo;
    private javax.swing.JButton btnImportarAlumno;
    private javax.swing.JButton btnImportarModulos;
    private javax.swing.JButton btnVaciarTablaAlumnos;
    private javax.swing.JButton btnVaciarTablaModulos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnyoEscolar;
    private javax.swing.JLabel lblApellidosAlumno;
    private javax.swing.JLabel lblBarraAnyoEscolar;
    private javax.swing.JLabel lblCodigoCiclo;
    private javax.swing.JLabel lblCodigoModulo;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblFechaFirma;
    private javax.swing.JLabel lblFechaSesion;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblNombreAlumno;
    private javax.swing.JLabel lblNombreCiclo;
    private javax.swing.JLabel lblNombreModulo;
    private javax.swing.JLabel lblPobalcion;
    private javax.swing.JPanel pnlAlumnos;
    private javax.swing.JPanel pnlDatosComunes;
    private javax.swing.JPanel pnlModulos;
    private javax.swing.JPanel pnlTipoAnexo;
    private javax.swing.JRadioButton rdbAnexoI;
    private javax.swing.JRadioButton rdbAnexoII;
    private javax.swing.JSpinner spnAnyoEscolarFin;
    private javax.swing.JSpinner spnAnyoEscolarIni;
    private javax.swing.JSpinner spnCurso;
    private javax.swing.JSpinner spnFechaFirma;
    private javax.swing.JSpinner spnFechaSesion;
    private javax.swing.JTable tblAlumnos;
    private javax.swing.JTable tblModulos;
    private javax.swing.JTextField txtApellidosAlumno;
    private javax.swing.JTextField txtCodigoCiclo;
    private javax.swing.JTextField txtCodigoModulo;
    private javax.swing.JTextField txtGrupo;
    private javax.swing.JTextField txtNombreAlumno;
    private javax.swing.JTextField txtNombreCiclo;
    private javax.swing.JTextField txtNombreModulo;
    private javax.swing.JTextField txtPoblacion;
    // End of variables declaration//GEN-END:variables
}
