/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package creadoranexosffe;

/**
 *
 * @author javimjprofe
 */
public class DialogoFin extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogoFin.class.getName());

    /**
     * Creates new form DialogoFin
     */
    public DialogoFin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensajeFin = new javax.swing.JLabel();
        btnAceptarFin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fin del proceos");
        setAlwaysOnTop(true);
        setName("dlgFin"); // NOI18N

        lblMensajeFin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensajeFin.setText("Proceso de generación de anexos finalizado correctamente.");
        lblMensajeFin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnAceptarFin.setText("Aceptar");
        btnAceptarFin.addActionListener(this::btnAceptarFinActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(lblMensajeFin)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(btnAceptarFin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(lblMensajeFin)
                .addGap(34, 34, 34)
                .addComponent(btnAceptarFin)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarFinActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAceptarFinActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarFin;
    private javax.swing.JLabel lblMensajeFin;
    // End of variables declaration//GEN-END:variables
}
