/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package creadoranexosffe;

/**
 *
 * @author javimjprofe
 */
public class DialogoError extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogoError.class.getName());

    /**
     * Creates new form dialogoError
     */
    public DialogoError(java.awt.Frame parent, boolean modal, String mensajeError) {
        super(parent, modal);
        initComponents();
        lblMensajeError.setText(mensajeError);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensajeError = new javax.swing.JLabel();
        btnMensajeErrorAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Error");
        setAlwaysOnTop(true);
        setIconImage(null);
        setName("dlgMensajeError"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        lblMensajeError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnMensajeErrorAceptar.setText("Aceptar");
        btnMensajeErrorAceptar.addActionListener(this::btnMensajeErrorAceptarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblMensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMensajeErrorAceptar)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblMensajeError)
                .addGap(18, 18, 18)
                .addComponent(btnMensajeErrorAceptar)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMensajeErrorAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensajeErrorAceptarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnMensajeErrorAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMensajeErrorAceptar;
    private javax.swing.JLabel lblMensajeError;
    // End of variables declaration//GEN-END:variables
}
