/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package creadoranexosffe;

/**
 *
 * @author javimjprofe
 */
public class DialogoInformacion extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogoInformacion.class.getName());
    private boolean eleccion = false;
    /**
     * Creates new form DialogoInformacion
     */
    public DialogoInformacion(java.awt.Frame parent, boolean modal, String texto) {
        super(parent, modal);
        initComponents();
        lblMensajeInformacion.setText(texto);
    }

    public boolean mostrarMensajeInformacion(){
        this.setVisible(true);
        return eleccion;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensajeInformacion = new javax.swing.JLabel();
        btnMensajeInformacionSi = new javax.swing.JButton();
        btnMensajeInformacionNo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(null);
        setName("dlgMensajeInformacion"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        btnMensajeInformacionSi.setText("Sí");
        btnMensajeInformacionSi.addActionListener(this::btnMensajeInformacionSiActionPerformed);

        btnMensajeInformacionNo.setText("No");
        btnMensajeInformacionNo.addActionListener(this::btnMensajeInformacionNoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(362, Short.MAX_VALUE)
                .addComponent(lblMensajeInformacion)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btnMensajeInformacionSi)
                .addGap(55, 55, 55)
                .addComponent(btnMensajeInformacionNo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblMensajeInformacion)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMensajeInformacionSi)
                    .addComponent(btnMensajeInformacionNo))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMensajeInformacionSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensajeInformacionSiActionPerformed
        eleccion = true;
        this.dispose();
    }//GEN-LAST:event_btnMensajeInformacionSiActionPerformed

    private void btnMensajeInformacionNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensajeInformacionNoActionPerformed
        eleccion = false;
        this.dispose();
    }//GEN-LAST:event_btnMensajeInformacionNoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMensajeInformacionNo;
    private javax.swing.JButton btnMensajeInformacionSi;
    private javax.swing.JLabel lblMensajeInformacion;
    // End of variables declaration//GEN-END:variables
}
